### ISSUE TITLE
Ipython pushes output off screen

### ISSUE THREAD

**Issue by ifuchs** [holzschu/a-shell#366]
All ipython output is pushed off screen. It can only be accessed by scrolling after each line is entered. Also, the ipython prompt is not on the line with the line number.

**Comment by holzschu** [comment]
I could not reproduce the issue. Were there any other steps, before launching ipython? Do you have a screenshot?

**Comment by ifuchs** [comment]
FWIW:The iPad is running iOS 15.3 beta. On another iPad running 15.2.1, I don't have the problem. 
https://user-images.githubusercontent.com/5650376/150649703-6f167065-69a5-4c05-8221-7af0972a7c4c.MOV

**Comment by ifuchs** [comment]
I posted a screen recording but not sure if that works on github or not.

**Comment by holzschu** [comment]
Thanks. I hope whatever is causing it is fixed before release.

**Comment by holzschu** [comment]
iOS 15.3 is currently a Release Candidate, meaning it's close to being released. I'll test ipython on my devices as soon as it is released. In the meantime, I won't release version 1.8.3, so debugging and testing can go faster (the first build for a new version takes longer to be approved than builds with the same version number).

**Comment by holzschu** [comment]
I've just tested on the iOS 15.3 release. `ipython` appears to work normally.

**Comment by ifuchs** [comment]
Problem persists on the iPad in landscape mode under iPadOS 15.3

**Comment by personalizedrefrigerator** [comment]
I have been experiencing similar issues on previous versions of iOS with both `ipython` and `jsi` (both use `prompt_toolkit`).
Testing it, I can also reproduce this on iOS (iPhone) 15.3 with `jsi` (portrait and landscape) and `ipython` (landscape).

**Comment by holzschu** [comment]
Thanks for confirming the issue and for the suggestion of the phone. I still cannot reproduce on my iPad (both portrait and landscape), but I have it on my iPhone (landscape only), so I can start looking for a cause.

**Comment by holzschu** [comment]
I think I've tracked it down to `prompt_toolkit` using `fcntl.ioctl` to get the window size, which fails, so falls back to the default size of `80x24`, which works almost all the time... except if the number of lines is less than 24.

Now I'm trying various fixes.

**Comment by holzschu** [comment]
Build 215 on TestFlight has a fix for this issue: https://testflight.apple.com/join/WUdKe3f4
Hopefully that works for you.
